### ISSUE TITLE
Bug: MultipleElementsArray can be initialized with empty array

### ISSUE THREAD

**Issue by ekscrypto** [lucaswkuipers/SafeTypes#7]
**Describe the bug**
MultipleElementsArray should enforce that all arrays contain multiple elements.  It is currently possible to initialize a MultiElementsArray using an empty array.

**To Reproduce**
```
    let array = MultiElementsArray<String>([])
```

**Expected behavior**
Compile time validation error or runtime error

**Screenshots**
![Screenshot 2024-03-05 at 15 08 09](https://github.com/lucaswkuipers/SafeTypes/assets/472733/b84f0b2f-0cf9-4d30-b775-ded88b63e671)

**Desktop (please complete the following information):**
 - OS: macOS 14.3.1, Xcode 15.2

**Comment by ekscrypto** [comment]
This initializer also compiles/runs without any error:
```
let array = MultiElementsArray("a")
```

![Screenshot 2024-03-05 at 15 12 39](https://github.com/lucaswkuipers/SafeTypes/assets/472733/d6b7b0d7-ef7c-4c09-8b95-f7014bbc1bf4)

**Comment by ekscrypto** [comment]
Again, same issue with:
```
    let array = MultiElementsArray([1])
```

**Comment by ekscrypto** [comment]
They are all failable initializers, it's expected.  The macro has to be used but the problem is the macros are not part of the base package for which the examples/docs are written.  It's a documentation issue.

**Comment by lucaswkuipers** [comment]
Thank you @ekscrypto for updating the issue as you added more information regarding it!

I'm working on writing the documentation in a clearer manner 😅

Cheers!
